kind: pipeline
type: docker
name: wtss-qgis

steps:
- name: build
  image: qgis/qgis:release-3_16
  commands:
  - pip3 install --upgrade pip
  - pip3 install --upgrade setuptools
  - pip3 install -e .[tests,docs]
  - ./run-tests.sh