#
# This file is part of Python QGIS Plugin for Web Time Series Services.
# Copyright (C) 2019-2020 INPE.
#
# Python QGIS Plugin for Web Time Series Services is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: 2

sphinx:
    configuration: wtss_plugin/help/source/conf.py

formats: []

python:
    version: 3.7

    install:
        - method: pip
          path: .
          extra_requirements:
              - docs